// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByB8YnMBKA3egXhWd1F8iv9SWVOTeNgJw',
    appId: '1:600577618956:web:18834b7314d9081fb9aa29',
    messagingSenderId: '600577618956',
    projectId: 'smart-lamp-iot-485d3',
    authDomain: 'smart-lamp-iot-485d3.firebaseapp.com',
    databaseURL: 'https://smart-lamp-iot-485d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-iot-485d3.firebasestorage.app',
    measurementId: 'G-DWQN66NREC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKCG61RQ3fZJchcsoBgxWwkKEeGFNcx7U',
    appId: '1:600577618956:android:963b88f59ddf36dcb9aa29',
    messagingSenderId: '600577618956',
    projectId: 'smart-lamp-iot-485d3',
    databaseURL: 'https://smart-lamp-iot-485d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-iot-485d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSM1tdgoWqbI2COYxkRXMfQeKnKB_XHjo',
    appId: '1:600577618956:ios:fc7f07ac72bad83bb9aa29',
    messagingSenderId: '600577618956',
    projectId: 'smart-lamp-iot-485d3',
    databaseURL: 'https://smart-lamp-iot-485d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-iot-485d3.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSM1tdgoWqbI2COYxkRXMfQeKnKB_XHjo',
    appId: '1:600577618956:ios:fc7f07ac72bad83bb9aa29',
    messagingSenderId: '600577618956',
    projectId: 'smart-lamp-iot-485d3',
    databaseURL: 'https://smart-lamp-iot-485d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-iot-485d3.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByB8YnMBKA3egXhWd1F8iv9SWVOTeNgJw',
    appId: '1:600577618956:web:9e93163258be7f28b9aa29',
    messagingSenderId: '600577618956',
    projectId: 'smart-lamp-iot-485d3',
    authDomain: 'smart-lamp-iot-485d3.firebaseapp.com',
    databaseURL: 'https://smart-lamp-iot-485d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lamp-iot-485d3.firebasestorage.app',
    measurementId: 'G-LC1FPWRP9M',
  );
}
